destination: ./_site
lsi:         false
port:        4000
highlighter: pygments
markdown:    kramdown
permalink:   date
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex
